name: Quote of the Day

on:
 schedule:
   - cron: "0 0 * * *" # Runs once daily at midnight UTC
 workflow_dispatch:

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: piyushsuthar/github-readme-quotes@main
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
